name: BrandonHarrington
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28131
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#160d09'
    - '#fdfdfd'
    - '#5f3e31'
    - '#a67463'
    - '#00c275'
  brandStrength: 0.8618437177501619
  lightness: 0.10002739657647908
  saturation: 0.6222729734145105
  rhythmicContrast: 0.531756051350385
purpose: []
