typography_spectrum: 0.28131
color:
  brandColors:
    - '#160d09'
    - '#fdfdfd'
    - '#5f3e31'
    - '#a67463'
    - '#00c275'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Brandon Harrington
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Guitarist and Utility
description: Can be yours!!
purpose: []
