layout_spectrum: 0.3392769789788872
typography_spectrum: 0.130026031518355
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.3564998717047274
  lightness: 0.5701031479984522
  saturation: 0.9808229820337147
  rhythmicContrast: 0.3360697205644101
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Brandon Harrington
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Guitarist and Utility
description: Can be yours!!
purpose: []
