name: BrandonHarrington
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28131
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#160d09'
    - '#fdfdfd'
    - '#5f3e31'
    - '#a67463'
    - '#00c275'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
